[project]
name = "ComfyUI-Simple_Square_Masks"
description = "ComfyUI simple square masks creation."
version = "0.0.0.3"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/zentrocdot/ComfyUI_Square_Masks"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "zentrocdot"
DisplayName = "ComfyUI-Simple_Image_To_Prompt"
Icon = "https://github.com/zentrocdot/ComfyUI_Square_Masks/blob/main/images/original_logo_512x512.png"
